-- ============================================================
-- SUPABASE SCHEMA: SIMPEG (Sistem Layanan Adm. Kepegawaian)
-- ============================================================
-- Jalankan seluruh file ini di Supabase Dashboard -> SQL Editor
-- ============================================================

-- Extension UUID (biasanya sudah aktif di Supabase)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================
-- 1. TABEL: data_utama
--    Sumber: sheet "Data Utama" di Spreadsheet
-- ============================================================
CREATE TABLE IF NOT EXISTS data_utama (
  id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  no                        TEXT,
  nip                       TEXT UNIQUE NOT NULL,
  karpeg                    TEXT,
  nidn                      TEXT,
  nuptk                     TEXT,
  nama_lengkap              TEXT,
  nama                      TEXT,
  nama_pada_upacara         TEXT,
  tmp_lhr                   TEXT,
  tgl_lhr                   TEXT,
  jns_kel                   TEXT,
  agama                     TEXT,
  status_menikah            TEXT,
  tmt_pengangkatan          TEXT,
  golongan                  TEXT,
  pangkat                   TEXT,
  tmt_gol                   TEXT,
  jabatan                   TEXT,
  jenis_jab                 TEXT,
  tmt_jab                   TEXT,
  kum                       TEXT,
  tmt_kum                   TEXT,
  pendidikan                TEXT,
  jurusan                   TEXT,
  thn_lulus                 TEXT,
  kepakaran                 TEXT,
  status_bekerja            TEXT,
  tmt_status_bekerja        TEXT,
  akhir_tmt_status_bekerja  TEXT,
  jenis_peg                 TEXT,
  status_kepegawaian        TEXT,
  tmt_pensiun_bup           TEXT,
  unit_es_ii                TEXT,
  unit_es_iii               TEXT,
  unit_es_iv                TEXT,
  tmt_awal_bekerja_di_undip TEXT,
  jalur_masuk               TEXT,
  keterangan                TEXT,
  created_at                TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_data_utama_nip  ON data_utama(nip);
CREATE INDEX IF NOT EXISTS idx_data_utama_nama ON data_utama(nama_lengkap);
CREATE INDEX IF NOT EXISTS idx_data_utama_unit ON data_utama(unit_es_ii);

-- ============================================================
-- 2. TABEL: user_roles
--    Sumber: sheet "User Roles"
-- ============================================================
CREATE TABLE IF NOT EXISTS user_roles (
  nip             TEXT PRIMARY KEY,
  nama            TEXT,
  role            TEXT NOT NULL DEFAULT 'normal'
                  CHECK (role IN ('normal','user','admin','super_admin')),
  diubah_oleh     TEXT,
  tanggal_diubah  TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 3. TABEL: templates
--    Sumber: sheet "Templates"
-- ============================================================
CREATE TABLE IF NOT EXISTS templates (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  judul       TEXT NOT NULL,
  file_id     TEXT NOT NULL,
  layanan     TEXT NOT NULL,
  sub_menu    TEXT NOT NULL,
  tipe        TEXT NOT NULL DEFAULT 'gdocs',
  dibuat_pada TIMESTAMPTZ DEFAULT NOW()
);

-- Safe for existing installations as well as new databases.
ALTER TABLE templates ADD COLUMN IF NOT EXISTS tipe TEXT DEFAULT 'gdocs';

CREATE INDEX IF NOT EXISTS idx_templates_layanan ON templates(layanan, sub_menu);

-- ============================================================
-- 4. TABEL: usulan_kp
--    Sumber: sheet "Usulan KP"
-- ============================================================
CREATE TABLE IF NOT EXISTS usulan_kp (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  batch_id              UUID,
  nip                   TEXT,
  nama                  TEXT,
  unit                  TEXT,
  diajukan_oleh_nip     TEXT,
  nama_pengaju          TEXT,
  tanggal_diajukan      TIMESTAMPTZ DEFAULT NOW(),
  file_url              TEXT,
  status                TEXT DEFAULT 'Diajukan',
  opsi_a_selesai_pada   TIMESTAMPTZ,
  opsi_b_selesai_pada   TIMESTAMPTZ,
  diproses_oleh_nip     TEXT
);

CREATE INDEX IF NOT EXISTS idx_usulan_kp_nip    ON usulan_kp(nip);
CREATE INDEX IF NOT EXISTS idx_usulan_kp_status ON usulan_kp(status);
CREATE INDEX IF NOT EXISTS idx_usulan_kp_unit   ON usulan_kp(unit);

-- ============================================================
-- 5. TABEL: usulan_pensiun
--    Sumber: sheet "Usulan Pensiun"
-- ============================================================
CREATE TABLE IF NOT EXISTS usulan_pensiun (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nip                  TEXT,
  nama                 TEXT,
  unit                 TEXT,
  jenis_pensiun        TEXT,
  diajukan_oleh_nip    TEXT,
  nama_pengaju         TEXT,
  tanggal_diajukan     TIMESTAMPTZ DEFAULT NOW(),
  file_url             TEXT,
  file_tambahan1_url   TEXT,
  file_tambahan1_label TEXT,
  file_tambahan2_url   TEXT,
  file_tambahan2_label TEXT,
  status               TEXT DEFAULT 'Diajukan',
  dpcp_selesai_pada    TIMESTAMPTZ,
  super_selesai_pada   TIMESTAMPTZ,
  diproses_oleh_nip    TEXT
);

CREATE INDEX IF NOT EXISTS idx_usulan_pensiun_nip    ON usulan_pensiun(nip);
CREATE INDEX IF NOT EXISTS idx_usulan_pensiun_status ON usulan_pensiun(status);
CREATE INDEX IF NOT EXISTS idx_usulan_pensiun_unit   ON usulan_pensiun(unit);

-- ============================================================
-- 6. ROW LEVEL SECURITY
--    Semua akses via service_role key dari api/rpc.js (bypass RLS)
-- ============================================================
ALTER TABLE data_utama     ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_roles     ENABLE ROW LEVEL SECURITY;
ALTER TABLE templates      ENABLE ROW LEVEL SECURITY;
ALTER TABLE usulan_kp      ENABLE ROW LEVEL SECURITY;
ALTER TABLE usulan_pensiun ENABLE ROW LEVEL SECURITY;

-- Larang akses public langsung (hanya lewat backend service_role)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='data_utama' AND policyname='deny_public_data_utama') THEN
    CREATE POLICY "deny_public_data_utama"     ON data_utama     FOR ALL TO public USING (false);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='user_roles' AND policyname='deny_public_user_roles') THEN
    CREATE POLICY "deny_public_user_roles"     ON user_roles     FOR ALL TO public USING (false);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='templates' AND policyname='deny_public_templates') THEN
    CREATE POLICY "deny_public_templates"      ON templates      FOR ALL TO public USING (false);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='usulan_kp' AND policyname='deny_public_usulan_kp') THEN
    CREATE POLICY "deny_public_usulan_kp"      ON usulan_kp      FOR ALL TO public USING (false);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='usulan_pensiun' AND policyname='deny_public_usulan_pensiun') THEN
    CREATE POLICY "deny_public_usulan_pensiun" ON usulan_pensiun FOR ALL TO public USING (false);
  END IF;
END $$;

-- ============================================================
-- 7. STORAGE BUCKET untuk lampiran file usulan
--    (Buat lewat Supabase Dashboard: Storage -> New Bucket)
--    Nama: lampiran-usulan, Private (public=false)
-- ============================================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('lampiran-usulan', 'lampiran-usulan', false)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- 8. TAMBAHAN UNTUK ALUR SK KENAIKAN PANGKAT (NON-ASN)
--    Jalankan bagian ini di Supabase SQL Editor jika sudah
--    pernah menjalankan schema di atas sebelumnya.
-- ============================================================

-- 8a. Kolom sub_role untuk admin/super_admin yang berperan sebagai
--     approver berjenjang SK KP (Staff → SPV → ... → Wakil Rektor)
ALTER TABLE user_roles ADD COLUMN IF NOT EXISTS sub_role TEXT
  CHECK (sub_role IN ('staff','supervisor','manajer','wakil_direktur','direktur','wakil_rektor','rektor'));

-- 8b. Kolom tambahan di usulan_kp untuk alur SK
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS nomor_surat_usul_unit   TEXT;
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS tgl_surat_usul           TEXT;
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS file_surat_usul_url      TEXT;
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS nomor_sk                 TEXT;
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS tmt_kp_baru              TEXT;
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS masa_kerja_kp_baru_tahun TEXT;
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS masa_kerja_kp_baru_bulan TEXT;
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS gaji_pokok_baru_kp       TEXT;
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS pangkat_baru             TEXT;
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS gol_baru                 TEXT;
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS sk_file_id               TEXT;
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS sk_pdf_url               TEXT;
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS sk_pdf_signed_url        TEXT;
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS sk_dibuat_pada           TIMESTAMPTZ;
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS sk_approval_step         TEXT DEFAULT 'staff';
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS sk_approval_log          JSONB DEFAULT '[]';
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS sk_selesai_pada          TIMESTAMPTZ;

-- 8c. Storage bucket khusus untuk PDF SK yang sudah ditandatangani
INSERT INTO storage.buckets (id, name, public)
VALUES ('sk-kp', 'sk-kp', false)
ON CONFLICT (id) DO NOTHING;

-- 8d. Index untuk performa query SK
CREATE INDEX IF NOT EXISTS idx_usulan_kp_sk_step ON usulan_kp(sk_approval_step);

-- 8e. RLS policy untuk bucket sk-kp (denied to public, same as lampiran-usulan)
ALTER TABLE usulan_kp ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='usulan_kp' AND policyname='deny_public_usulan_kp') THEN
    CREATE POLICY "deny_public_usulan_kp" ON usulan_kp FOR ALL TO public USING (false);
  END IF;
END $$;
