-- ============================================================
-- SUPABASE SCHEMA: SIMPEG (Sistem Layanan Adm. Kepegawaian)
-- ============================================================
-- Jalankan seluruh file ini di Supabase Dashboard -> SQL Editor
-- ============================================================

-- Extension UUID (biasanya sudah aktif di Supabase)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================
-- 1. TABEL: data_utama
--    Sumber: sheet "Data Utama" di Spreadsheet
-- ============================================================
CREATE TABLE IF NOT EXISTS data_utama (
  id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  no                        TEXT,
  nip                       TEXT UNIQUE NOT NULL,
  karpeg                    TEXT,
  nidn                      TEXT,
  nuptk                     TEXT,
  nama_lengkap              TEXT,
  nama                      TEXT,
  nama_pada_upacara         TEXT,
  tmp_lhr                   TEXT,
  tgl_lhr                   TEXT,
  jns_kel                   TEXT,
  agama                     TEXT,
  status_menikah            TEXT,
  tmt_pengangkatan          TEXT,
  golongan                  TEXT,
  pangkat                   TEXT,
  tmt_gol                   TEXT,
  jabatan                   TEXT,
  jenis_jab                 TEXT,
  tmt_jab                   TEXT,
  kum                       TEXT,
  tmt_kum                   TEXT,
  pendidikan                TEXT,
  jurusan                   TEXT,
  thn_lulus                 TEXT,
  kepakaran                 TEXT,
  status_bekerja            TEXT,
  tmt_status_bekerja        TEXT,
  akhir_tmt_status_bekerja  TEXT,
  jenis_peg                 TEXT,
  status_kepegawaian        TEXT,
  tmt_pensiun_bup           TEXT,
  unit_es_ii                TEXT,
  unit_es_iii               TEXT,
  unit_es_iv                TEXT,
  tmt_awal_bekerja_di_undip TEXT,
  jalur_masuk               TEXT,
  keterangan                TEXT,
  created_at                TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_data_utama_nip  ON data_utama(nip);
CREATE INDEX IF NOT EXISTS idx_data_utama_nama ON data_utama(nama_lengkap);
CREATE INDEX IF NOT EXISTS idx_data_utama_unit ON data_utama(unit_es_ii);

-- ============================================================
-- 2. TABEL: user_roles
--    Sumber: sheet "User Roles"
-- ============================================================
CREATE TABLE IF NOT EXISTS user_roles (
  nip             TEXT PRIMARY KEY,
  nama            TEXT,
  role            TEXT NOT NULL DEFAULT 'normal'
                  CHECK (role IN ('normal','user','admin','super_admin')),
  diubah_oleh     TEXT,
  tanggal_diubah  TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 3. TABEL: templates
--    Sumber: sheet "Templates"
-- ============================================================
CREATE TABLE IF NOT EXISTS templates (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  judul       TEXT NOT NULL,
  file_id     TEXT NOT NULL,
  layanan     TEXT NOT NULL,
  sub_menu    TEXT NOT NULL,
  tipe        TEXT NOT NULL DEFAULT 'gdocs',
  dibuat_pada TIMESTAMPTZ DEFAULT NOW()
);

-- Safe for existing installations as well as new databases.
ALTER TABLE templates ADD COLUMN IF NOT EXISTS tipe TEXT DEFAULT 'gdocs';

CREATE INDEX IF NOT EXISTS idx_templates_layanan ON templates(layanan, sub_menu);

-- ============================================================
-- 4. TABEL: usulan_kp
--    Sumber: sheet "Usulan KP"
-- ============================================================
CREATE TABLE IF NOT EXISTS usulan_kp (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  batch_id              UUID,
  nip                   TEXT,
  nama                  TEXT,
  unit                  TEXT,
  jabatan               TEXT,
  golongan_lama         TEXT,
  golongan_baru         TEXT,
  diajukan_oleh_nip     TEXT,
  nama_pengaju          TEXT,
  tanggal_diajukan      TIMESTAMPTZ DEFAULT NOW(),
  file_url              TEXT,
  status                TEXT DEFAULT 'Diterima DSDM',
  tmt                   TEXT,
  opsi_a_selesai_pada   TIMESTAMPTZ,
  opsi_b_selesai_pada   TIMESTAMPTZ,
  diproses_oleh_nip     TEXT
);

ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS tmt TEXT;
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS golongan_lama TEXT;
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS golongan_baru TEXT;
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS jabatan TEXT;
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS jenis_pegawai TEXT DEFAULT 'Tendik';
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS status_kepegawaian TEXT DEFAULT 'PNS';

CREATE INDEX IF NOT EXISTS idx_usulan_kp_nip    ON usulan_kp(nip);
CREATE INDEX IF NOT EXISTS idx_usulan_kp_status ON usulan_kp(status);
CREATE INDEX IF NOT EXISTS idx_usulan_kp_unit   ON usulan_kp(unit);
CREATE INDEX IF NOT EXISTS idx_usulan_kp_tmt    ON usulan_kp(tmt);

-- ============================================================
-- 5. TABEL: usulan_pensiun
--    Sumber: sheet "Usulan Pensiun"
-- ============================================================
CREATE TABLE IF NOT EXISTS usulan_pensiun (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nip                  TEXT,
  nama                 TEXT,
  unit                 TEXT,
  jenis_pensiun        TEXT,
  diajukan_oleh_nip    TEXT,
  nama_pengaju         TEXT,
  tanggal_diajukan     TIMESTAMPTZ DEFAULT NOW(),
  file_url             TEXT,
  file_tambahan1_url   TEXT,
  file_tambahan1_label TEXT,
  file_tambahan2_url   TEXT,
  file_tambahan2_label TEXT,
  status               TEXT DEFAULT 'Diajukan',
  dpcp_selesai_pada    TIMESTAMPTZ,
  super_selesai_pada   TIMESTAMPTZ,
  diproses_oleh_nip    TEXT
);

CREATE INDEX IF NOT EXISTS idx_usulan_pensiun_nip    ON usulan_pensiun(nip);
CREATE INDEX IF NOT EXISTS idx_usulan_pensiun_status ON usulan_pensiun(status);
CREATE INDEX IF NOT EXISTS idx_usulan_pensiun_unit   ON usulan_pensiun(unit);

-- ============================================================
-- 6. ROW LEVEL SECURITY
--    Semua akses via service_role key dari api/rpc.js (bypass RLS)
-- ============================================================
ALTER TABLE data_utama     ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_roles     ENABLE ROW LEVEL SECURITY;
ALTER TABLE templates      ENABLE ROW LEVEL SECURITY;
ALTER TABLE usulan_kp      ENABLE ROW LEVEL SECURITY;
ALTER TABLE usulan_pensiun ENABLE ROW LEVEL SECURITY;

-- Larang akses public langsung (hanya lewat backend service_role)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='data_utama' AND policyname='deny_public_data_utama') THEN
    CREATE POLICY "deny_public_data_utama"     ON data_utama     FOR ALL TO public USING (false);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='user_roles' AND policyname='deny_public_user_roles') THEN
    CREATE POLICY "deny_public_user_roles"     ON user_roles     FOR ALL TO public USING (false);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='templates' AND policyname='deny_public_templates') THEN
    CREATE POLICY "deny_public_templates"      ON templates      FOR ALL TO public USING (false);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='usulan_kp' AND policyname='deny_public_usulan_kp') THEN
    CREATE POLICY "deny_public_usulan_kp"      ON usulan_kp      FOR ALL TO public USING (false);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='usulan_pensiun' AND policyname='deny_public_usulan_pensiun') THEN
    CREATE POLICY "deny_public_usulan_pensiun" ON usulan_pensiun FOR ALL TO public USING (false);
  END IF;
END $$;

-- ============================================================
-- 7. STORAGE BUCKET untuk lampiran file usulan
--    (Buat lewat Supabase Dashboard: Storage -> New Bucket)
--    Nama: lampiran-usulan, Private (public=false)
-- ============================================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('lampiran-usulan', 'lampiran-usulan', false)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- 8. TAMBAHAN UNTUK ALUR SK KENAIKAN PANGKAT (NON-ASN)
--    Jalankan bagian ini di Supabase SQL Editor jika sudah
--    pernah menjalankan schema di atas sebelumnya.
-- ============================================================

-- 8a. Kolom sub_role untuk admin/super_admin yang berperan sebagai
--     approver berjenjang SK KP (Staff → SPV → ... → Wakil Rektor)
ALTER TABLE user_roles ADD COLUMN IF NOT EXISTS sub_role TEXT
  CHECK (sub_role IN ('staff','supervisor','manajer','wakil_direktur','direktur','wakil_rektor','rektor'));

-- 8b. Kolom tambahan di usulan_kp untuk alur SK
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS nomor_surat_usul_unit   TEXT;
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS tgl_surat_usul           TEXT;
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS file_surat_usul_url      TEXT;
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS nomor_sk                 TEXT;
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS tmt_kp_baru              TEXT;
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS masa_kerja_kp_baru_tahun TEXT;
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS masa_kerja_kp_baru_bulan TEXT;
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS gaji_pokok_baru_kp       TEXT;
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS pangkat_baru             TEXT;
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS gol_baru                 TEXT;
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS sk_file_id               TEXT;
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS sk_pdf_url               TEXT;
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS sk_pdf_signed_url        TEXT;
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS sk_dibuat_pada           TIMESTAMPTZ;
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS sk_approval_step         TEXT DEFAULT 'staff';
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS sk_approval_log          JSONB DEFAULT '[]';
ALTER TABLE usulan_kp ADD COLUMN IF NOT EXISTS sk_selesai_pada          TIMESTAMPTZ;

-- 8c. Storage bucket khusus untuk PDF SK yang sudah ditandatangani
INSERT INTO storage.buckets (id, name, public)
VALUES ('sk-kp', 'sk-kp', false)
ON CONFLICT (id) DO NOTHING;

-- 8d. Index untuk performa query SK
CREATE INDEX IF NOT EXISTS idx_usulan_kp_sk_step ON usulan_kp(sk_approval_step);

-- 8e. RLS policy untuk bucket sk-kp (denied to public, same as lampiran-usulan)
ALTER TABLE usulan_kp ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='usulan_kp' AND policyname='deny_public_usulan_kp') THEN
    CREATE POLICY "deny_public_usulan_kp" ON usulan_kp FOR ALL TO public USING (false);
  END IF;
END $$;

-- ============================================================
-- 9. TABEL: akses_kontrak_mandiri
--    Kontrol akses mandiri pengajuan Kontrak oleh pegawai (role normal)
-- ============================================================
CREATE TABLE IF NOT EXISTS akses_kontrak_mandiri (
  kategori        TEXT PRIMARY KEY,
  diizinkan       BOOLEAN NOT NULL DEFAULT FALSE,
  diubah_oleh     TEXT,
  tanggal_diubah  TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE akses_kontrak_mandiri ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='akses_kontrak_mandiri' AND policyname='deny_public_akses_kontrak_mandiri') THEN
    CREATE POLICY "deny_public_akses_kontrak_mandiri" ON akses_kontrak_mandiri FOR ALL TO public USING (false);
  END IF;
END $$;

-- ============================================================
-- 10. TABEL: usulan_kontrak
--     Pengajuan usulan Kontrak oleh pegawai / admin
-- ============================================================
CREATE TABLE IF NOT EXISTS usulan_kontrak (
  id                          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nip                         TEXT,
  nama                        TEXT,
  unit                        TEXT,
  email                       TEXT,
  tahun                       TEXT,
  jenis_usulan                TEXT,
  evaluasi_kinerja            TEXT,
  layanan                     TEXT,
  sub_menu                    TEXT,
  form_data                   JSONB DEFAULT '{}',
  ktp_url                     TEXT,
  ktp_approved                BOOLEAN DEFAULT FALSE,
  kk_url                      TEXT,
  kk_approved                 BOOLEAN DEFAULT FALSE,
  pas_foto_url                TEXT,
  pas_foto_approved           BOOLEAN DEFAULT FALSE,
  ijazah_transkrip_url        TEXT,
  ijazah_transkrip_approved   BOOLEAN DEFAULT FALSE,
  surat_pengantar_url         TEXT,
  surat_pengantar_approved    BOOLEAN DEFAULT FALSE,
  surat_lamaran_url           TEXT,
  surat_lamaran_approved      BOOLEAN DEFAULT FALSE,
  sim_ab_url                  TEXT,
  sim_ab_approved             BOOLEAN DEFAULT FALSE,
  str_aktif_url               TEXT,
  str_aktif_approved          BOOLEAN DEFAULT FALSE,
  keterangan_sehat_url        TEXT,
  keterangan_sehat_approved   BOOLEAN DEFAULT FALSE,
  diajukan_oleh_nip           TEXT,
  nama_pengaju                TEXT,
  tanggal_diajukan            TIMESTAMPTZ DEFAULT NOW(),
  status                      TEXT DEFAULT 'Diajukan',
  perjanjian_dibuat           BOOLEAN DEFAULT FALSE,
  diproses_oleh_nip           TEXT
);

CREATE INDEX IF NOT EXISTS idx_usulan_kontrak_nip    ON usulan_kontrak(nip);
CREATE INDEX IF NOT EXISTS idx_usulan_kontrak_status ON usulan_kontrak(status);
CREATE INDEX IF NOT EXISTS idx_usulan_kontrak_unit   ON usulan_kontrak(unit);

ALTER TABLE usulan_kontrak ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='usulan_kontrak' AND policyname='deny_public_usulan_kontrak') THEN
    CREATE POLICY "deny_public_usulan_kontrak" ON usulan_kontrak FOR ALL TO public USING (false);
  END IF;
END $$;

-- ============================================================
-- 11. TABEL: usulan_pmk
--     Pengajuan usulan Peninjauan Masa Kerja (PMK) PNS
-- ============================================================
CREATE TABLE IF NOT EXISTS usulan_pmk (
  id                                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nip                               TEXT NOT NULL,
  nama                              TEXT,
  unit                              TEXT,
  nomor_surat_usul_pmk              TEXT,
  file_surat_usul_pmk_url           TEXT,
  file_surat_usul_pmk_approved      BOOLEAN DEFAULT FALSE,
  file_kp_terakhir_url              TEXT,
  file_kp_terakhir_approved         BOOLEAN DEFAULT FALSE,
  file_sk_kerja_url                 TEXT,
  file_sk_kerja_approved            BOOLEAN DEFAULT FALSE,
  file_sk_pns_url                   TEXT,
  file_sk_pns_approved              BOOLEAN DEFAULT FALSE,
  file_phk_url                      TEXT,
  file_phk_approved                 BOOLEAN DEFAULT FALSE,
  file_gaji_url                     TEXT,
  file_gaji_approved                BOOLEAN DEFAULT FALSE,
  file_kontrak_url                  TEXT,
  file_kontrak_approved             BOOLEAN DEFAULT FALSE,
  file_melamar_cpns_url             TEXT,
  jenis_usulan                      TEXT DEFAULT 'PMK',
  jenjang_pendidikan_terbaru        TEXT,
  file_ijazah_terbaru_url           TEXT,
  file_ijazah_terbaru_approved      BOOLEAN DEFAULT FALSE,
  file_transkrip_terbaru_url        TEXT,
  file_transkrip_terbaru_approved   BOOLEAN DEFAULT FALSE,
  file_sk_ijin_belajar_url          TEXT,
  file_sk_ijin_belajar_approved     BOOLEAN DEFAULT FALSE,
  file_sk_pengaktifan_url           TEXT,
  file_sk_pengaktifan_approved      BOOLEAN DEFAULT FALSE,
  file_penyetaraan_ijazah_url       TEXT,
  file_penyetaraan_ijazah_approved  BOOLEAN DEFAULT FALSE,
  diajukan_oleh_nip                 TEXT,
  nama_pengaju                      TEXT,
  tanggal_diajukan                  TIMESTAMPTZ DEFAULT NOW(),
  status                            TEXT DEFAULT 'Diajukan',
  diproses_oleh_nip                 TEXT,
  tanggal_diproses                  TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_usulan_pmk_nip    ON usulan_pmk(nip);
CREATE INDEX IF NOT EXISTS idx_usulan_pmk_status ON usulan_pmk(status);
CREATE INDEX IF NOT EXISTS idx_usulan_pmk_unit   ON usulan_pmk(unit);

ALTER TABLE usulan_pmk ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='usulan_pmk' AND policyname='deny_public_usulan_pmk') THEN
    CREATE POLICY "deny_public_usulan_pmk" ON usulan_pmk FOR ALL TO public USING (false);
  END IF;
END $$;

-- Migrasi aman untuk database usulan_pmk yang sudah ada sebelum penambahan PG
ALTER TABLE usulan_pmk ADD COLUMN IF NOT EXISTS jenis_usulan                      TEXT DEFAULT 'PMK';
ALTER TABLE usulan_pmk ADD COLUMN IF NOT EXISTS jenjang_pendidikan_terbaru        TEXT;
ALTER TABLE usulan_pmk ADD COLUMN IF NOT EXISTS file_ijazah_terbaru_url           TEXT;
ALTER TABLE usulan_pmk ADD COLUMN IF NOT EXISTS file_ijazah_terbaru_approved      BOOLEAN DEFAULT FALSE;
ALTER TABLE usulan_pmk ADD COLUMN IF NOT EXISTS file_transkrip_terbaru_url        TEXT;
ALTER TABLE usulan_pmk ADD COLUMN IF NOT EXISTS file_transkrip_terbaru_approved   BOOLEAN DEFAULT FALSE;
ALTER TABLE usulan_pmk ADD COLUMN IF NOT EXISTS file_sk_ijin_belajar_url          TEXT;
ALTER TABLE usulan_pmk ADD COLUMN IF NOT EXISTS file_sk_ijin_belajar_approved     BOOLEAN DEFAULT FALSE;
ALTER TABLE usulan_pmk ADD COLUMN IF NOT EXISTS file_sk_pengaktifan_url           TEXT;
ALTER TABLE usulan_pmk ADD COLUMN IF NOT EXISTS file_sk_pengaktifan_approved      BOOLEAN DEFAULT FALSE;
ALTER TABLE usulan_pmk ADD COLUMN IF NOT EXISTS file_penyetaraan_ijazah_url       TEXT;
ALTER TABLE usulan_pmk ADD COLUMN IF NOT EXISTS file_penyetaraan_ijazah_approved  BOOLEAN DEFAULT FALSE;

-- Migrasi aman untuk database usulan_kontrak yang sudah ada
ALTER TABLE usulan_kontrak ADD COLUMN IF NOT EXISTS form_data                   JSONB DEFAULT '{}';
ALTER TABLE usulan_kontrak ADD COLUMN IF NOT EXISTS ktp_url                     TEXT;
ALTER TABLE usulan_kontrak ADD COLUMN IF NOT EXISTS ktp_approved                BOOLEAN DEFAULT FALSE;
ALTER TABLE usulan_kontrak ADD COLUMN IF NOT EXISTS kk_url                      TEXT;
ALTER TABLE usulan_kontrak ADD COLUMN IF NOT EXISTS kk_approved                 BOOLEAN DEFAULT FALSE;
ALTER TABLE usulan_kontrak ADD COLUMN IF NOT EXISTS pas_foto_url                TEXT;
ALTER TABLE usulan_kontrak ADD COLUMN IF NOT EXISTS pas_foto_approved           BOOLEAN DEFAULT FALSE;
ALTER TABLE usulan_kontrak ADD COLUMN IF NOT EXISTS ijazah_transkrip_url        TEXT;
ALTER TABLE usulan_kontrak ADD COLUMN IF NOT EXISTS ijazah_transkrip_approved   BOOLEAN DEFAULT FALSE;
ALTER TABLE usulan_kontrak ADD COLUMN IF NOT EXISTS surat_pengantar_url         TEXT;
ALTER TABLE usulan_kontrak ADD COLUMN IF NOT EXISTS surat_pengantar_approved    BOOLEAN DEFAULT FALSE;
ALTER TABLE usulan_kontrak ADD COLUMN IF NOT EXISTS surat_lamaran_url           TEXT;
ALTER TABLE usulan_kontrak ADD COLUMN IF NOT EXISTS surat_lamaran_approved      BOOLEAN DEFAULT FALSE;
ALTER TABLE usulan_kontrak ADD COLUMN IF NOT EXISTS sim_ab_url                  TEXT;
ALTER TABLE usulan_kontrak ADD COLUMN IF NOT EXISTS sim_ab_approved             BOOLEAN DEFAULT FALSE;
ALTER TABLE usulan_kontrak ADD COLUMN IF NOT EXISTS str_aktif_url               TEXT;
ALTER TABLE usulan_kontrak ADD COLUMN IF NOT EXISTS str_aktif_approved          BOOLEAN DEFAULT FALSE;
ALTER TABLE usulan_kontrak ADD COLUMN IF NOT EXISTS keterangan_sehat_url        TEXT;
ALTER TABLE usulan_kontrak ADD COLUMN IF NOT EXISTS keterangan_sehat_approved   BOOLEAN DEFAULT FALSE;
ALTER TABLE usulan_kontrak ADD COLUMN IF NOT EXISTS perjanjian_dibuat           BOOLEAN DEFAULT FALSE;

-- ============================================================
-- 12. TAMBAHAN UNTUK ALUR SK PENSIUN (PEGAWAI UNDIP NON-ASN)
-- ============================================================
ALTER TABLE usulan_pensiun ADD COLUMN IF NOT EXISTS sk_nomor       TEXT;
ALTER TABLE usulan_pensiun ADD COLUMN IF NOT EXISTS sk_tmt         TEXT;
ALTER TABLE usulan_pensiun ADD COLUMN IF NOT EXISTS sk_file_id     TEXT;
ALTER TABLE usulan_pensiun ADD COLUMN IF NOT EXISTS sk_pdf_url     TEXT;
ALTER TABLE usulan_pensiun ADD COLUMN IF NOT EXISTS sk_dibuat_pada TIMESTAMPTZ;
ALTER TABLE usulan_pensiun ADD COLUMN IF NOT EXISTS form_data      JSONB DEFAULT '{}';

-- ============================================================
-- 13. TABEL: pimpinan
--     Sumber: sheet "Pimpinan"
-- ============================================================
CREATE TABLE IF NOT EXISTS pimpinan (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_pimpinan TEXT,
  unit_es_ii    TEXT UNIQUE NOT NULL,
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE pimpinan ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='pimpinan' AND policyname='deny_public_pimpinan') THEN
    CREATE POLICY "deny_public_pimpinan" ON pimpinan FOR ALL TO public USING (false);
  END IF;
END $$;

-- ============================================================
-- 14. TABEL: jenis_tutam
--     Sumber: sheet "Jenis tutam"
-- ============================================================
CREATE TABLE IF NOT EXISTS jenis_tutam (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  no          TEXT,
  jenis_tutam TEXT UNIQUE NOT NULL,
  departemen  TEXT,
  unit_es_ii  TEXT,
  keterangan  TEXT,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- Perintah penambahan kolom aman jika tabel jenis_tutam sudah ada di Supabase:
ALTER TABLE jenis_tutam ADD COLUMN IF NOT EXISTS no         TEXT;
ALTER TABLE jenis_tutam ADD COLUMN IF NOT EXISTS departemen TEXT;
ALTER TABLE jenis_tutam ADD COLUMN IF NOT EXISTS unit_es_ii TEXT;
ALTER TABLE jenis_tutam ADD COLUMN IF NOT EXISTS keterangan TEXT;

ALTER TABLE jenis_tutam ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='jenis_tutam' AND policyname='deny_public_jenis_tutam') THEN
    CREATE POLICY "deny_public_jenis_tutam" ON jenis_tutam FOR ALL TO public USING (false);
  END IF;
END $$;

-- ============================================================
-- 15. TAMBAHAN KOLOM: pimpinan & jenis_tutam
--     Untuk modul Buat SK (auto-resolve placeholder)
-- ============================================================

-- Kategori pimpinan: 'Dekan', 'Wakil Dekan', 'Direktur', dsb
-- Digunakan untuk auto-resolve {{pimpinan}} di template SK
-- Contoh: jika kategori_pimpinan='Dekan' → {{pimpinan}} = 'Pertimbangan Senat Akademik'
--         jika kategori_pimpinan='Wakil Dekan' → {{pimpinan}} = 'Surat Dekan'
ALTER TABLE pimpinan ADD COLUMN IF NOT EXISTS kategori_pimpinan TEXT;

-- Nama detail jabatan tutam (untuk {{nama_jabatan}} di template SK)
ALTER TABLE jenis_tutam ADD COLUMN IF NOT EXISTS nama_detail TEXT;

-- ============================================================
-- 16. TABEL: usulan_sk
--     Pengajuan usulan SK/Surat dari user ke admin
-- ============================================================
CREATE TABLE IF NOT EXISTS usulan_sk (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Pengaju
  diajukan_oleh_nip     TEXT NOT NULL,
  nama_pengaju          TEXT,
  tanggal_diajukan      TIMESTAMPTZ DEFAULT NOW(),

  -- Target (pegawai yang diusulkan)
  nip_target            TEXT,
  nama_target           TEXT,
  unit_es_ii            TEXT,

  -- Jenis & Dokumen Usulan
  -- Nilai: 'Kaprodi', 'Kadep', 'Sekprodi', 'PLT', 'PLH'
  jenis_proposal        TEXT NOT NULL,
  nomor_surat_usul      TEXT,
  tgl_surat_usul        TEXT,
  file_surat_usul_url   TEXT,

  -- Validasi khusus Sekprodi: harus > 100
  jumlah_mahasiswa      INTEGER,

  -- Status: 'Diajukan' → 'Diverifikasi' → 'SK Dibuat' → 'Selesai' → 'Ditolak'
  status                TEXT DEFAULT 'Diajukan'
                        CHECK (status IN ('Diajukan','Diverifikasi','SK Dibuat','Selesai','Ditolak')),

  catatan_admin         TEXT,
  diproses_oleh_nip     TEXT,
  tanggal_diproses      TIMESTAMPTZ,

  -- Link ke SK yang sudah dibuat (opsional)
  sk_id                 UUID,

  created_at            TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_usulan_sk_pengaju  ON usulan_sk(diajukan_oleh_nip);
CREATE INDEX IF NOT EXISTS idx_usulan_sk_target   ON usulan_sk(nip_target);
CREATE INDEX IF NOT EXISTS idx_usulan_sk_status   ON usulan_sk(status);
CREATE INDEX IF NOT EXISTS idx_usulan_sk_unit     ON usulan_sk(unit_es_ii);

ALTER TABLE usulan_sk ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='usulan_sk' AND policyname='deny_public_usulan_sk') THEN
    CREATE POLICY "deny_public_usulan_sk" ON usulan_sk FOR ALL TO public USING (false);
  END IF;
END $$;

-- ============================================================
-- 17. TABEL: sk_generated
--     Riwayat SK yang pernah dibuat oleh admin
-- ============================================================
CREATE TABLE IF NOT EXISTS sk_generated (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Jenis SK: 'SK CPTU','SK PTU 100%','SK Tutam Kadep & Kaprodi',
  --           'SK Tutam Sekprodi','Surat PLT','Surat PLH',
  --           'SK Tutam Struktural','SK Tutam Dekan Wadek'
  jenis_sk                TEXT NOT NULL,

  template_id             UUID,        -- FK ke tabel templates (opsional)
  unit_es_ii              TEXT,

  -- Snapshot form data & loop tabel pejabat (JSON)
  form_data               JSONB DEFAULT '{}',
  pejabat_dilantik        JSONB DEFAULT '[]',
  pejabat_diberhentikan   JSONB DEFAULT '[]',

  -- Output dokumen
  output_file_url         TEXT,
  output_file_id          TEXT,
  output_type             TEXT DEFAULT 'docx',  -- 'docx' | 'gdocs'

  -- Link ke usulan asal (opsional)
  usulan_sk_id            UUID,

  -- Audit
  dibuat_oleh_nip         TEXT NOT NULL,
  nama_pembuat            TEXT,
  dibuat_pada             TIMESTAMPTZ DEFAULT NOW(),

  nomor_sk                TEXT,
  tgl_sk                  TEXT
);

CREATE INDEX IF NOT EXISTS idx_sk_generated_jenis  ON sk_generated(jenis_sk);
CREATE INDEX IF NOT EXISTS idx_sk_generated_unit   ON sk_generated(unit_es_ii);
CREATE INDEX IF NOT EXISTS idx_sk_generated_dibuat ON sk_generated(dibuat_oleh_nip);

ALTER TABLE sk_generated ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='sk_generated' AND policyname='deny_public_sk_generated') THEN
    CREATE POLICY "deny_public_sk_generated" ON sk_generated FOR ALL TO public USING (false);
  END IF;
END $$;

-- ============================================================
-- 18. TABEL: jenis_surat
--     Penyimpanan jenis surat dinamis (In-place add)
-- ============================================================
CREATE TABLE IF NOT EXISTS jenis_surat (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nama        TEXT UNIQUE NOT NULL,
  layanan     TEXT DEFAULT 'Buat SK dan Surat',
  dibuat_pada TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_jenis_surat_nama ON jenis_surat(nama);

INSERT INTO jenis_surat (nama, layanan) VALUES
  ('SK CPTU', 'Buat SK dan Surat'),
  ('SK PTU 100%', 'Buat SK dan Surat'),
  ('SK Tutam Kadep & Kaprodi', 'Buat SK dan Surat'),
  ('SK Tutam Sekprodi', 'Buat SK dan Surat'),
  ('Surat PLT', 'Buat SK dan Surat'),
  ('Surat PLH', 'Buat SK dan Surat'),
  ('SK Tutam Struktural', 'Buat SK dan Surat'),
  ('SK Tutam Dekan Wadek', 'Buat SK dan Surat')
ON CONFLICT (nama) DO NOTHING;

ALTER TABLE jenis_surat ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='jenis_surat' AND policyname='deny_public_jenis_surat') THEN
    CREATE POLICY "deny_public_jenis_surat" ON jenis_surat FOR ALL TO public USING (false);
  END IF;
END $$;

