-- ==============================================================================
-- MIGRATION: 20260909000001_pembaruan_kontrak_tendik.sql
-- Kategori: Alur Pembaruan Kontrak Tendik (Auto-Assign Atasan, SKP Atasan, Kelengkapan Berkas)
-- ==============================================================================

-- 1. TABEL: atasan_langsung
--    Menyimpan data pejabat atasan langsung untuk auto-assign berdasarkan matching prodi (unit_es_iv pengusul)
CREATE TABLE IF NOT EXISTS atasan_langsung (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nip           TEXT NOT NULL,
  nama_lengkap  TEXT NOT NULL,
  pangkat       TEXT,
  golongan      TEXT,
  jabatan       TEXT,
  unit_es_ii    TEXT,
  prodi         TEXT UNIQUE NOT NULL, -- Kunci matching 1-on-1 dengan data_utama.unit_es_iv
  detail_tutam  TEXT,                -- Sumber tutam_atasan_langsung di dokumen SKP
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_atasan_langsung_prodi ON atasan_langsung(prodi);
CREATE INDEX IF NOT EXISTS idx_atasan_langsung_nip   ON atasan_langsung(nip);

-- Aktifkan RLS untuk tabel atasan_langsung
ALTER TABLE atasan_langsung ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='atasan_langsung' AND policyname='deny_public_atasan_langsung') THEN
    CREATE POLICY "deny_public_atasan_langsung" ON atasan_langsung FOR ALL TO public USING (false);
  END IF;
END $$;

-- 2. Tambah kolom pendukung alur kelengkapan berkas pasca-approval di usulan_kontrak
ALTER TABLE usulan_kontrak ADD COLUMN IF NOT EXISTS berkas_kelengkapan_submitted BOOLEAN DEFAULT FALSE;
ALTER TABLE usulan_kontrak ADD COLUMN IF NOT EXISTS berkas_kelengkapan_status    TEXT DEFAULT 'pending';
ALTER TABLE usulan_kontrak ADD COLUMN IF NOT EXISTS berkas_kelengkapan_data      JSONB DEFAULT '{}';
ALTER TABLE usulan_kontrak ADD COLUMN IF NOT EXISTS notifikasi_kelayakan_dilihat BOOLEAN DEFAULT FALSE;

-- 3. Migrasi data status / enum lama -> status baru
UPDATE usulan_kontrak SET status = 'evaluated_renewed' WHERE status = 'evaluated_extend';
UPDATE usulan_kontrak SET status = 'evaluated_not_renewed' WHERE status = 'evaluated_not_extend';
UPDATE usulan_kontrak SET status = 'closed_not_renewed' WHERE status = 'closed_not_extended';
